name: stm32-linux-bootloader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang_format:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.15
      with:
        clangFormatVersion: 15

  build:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: sudo apt update && sudo apt install libtinfo5
    - name: Install dependencies
      run: ./bootstrap.sh
    - name: Build with CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/cortex-m7.cmake -DCMAKE_SYSTEM_NAME=Generic'
        buildDirectory: '${{ github.workspace }}/build'
